version: "3"

services:
  api:
    build: ./
    container_name: api
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    networks:
      - demo_network
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - demo_network
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - 27017:27017
      volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
      networks:
        - demo_network
volumes:
  redis-data:
  mongo-data:
  mongo-config:
networks:
  demo_network:
    driver: bridge